name: 'CommandDefender'
version: ${project.version}
description: ${project.description}
author: lokka30
main: me.lokka30.commanddefender.CommandDefender
api-version: '1.13'

commands:
  commanddefender:
    aliases: [ cd, cmddefender ]
    description: Manage CommandDefender.
    usage: /<command> [reload/backup/info]

permissions:
  commanddefender.*:
    description: Access to all of the plugin's permissions.
    default: op
    children:
      commanddefender.allow.*: true
      commanddefender.command.*: true
      commanddefender.bypass-colon-blocker: true

  commanddefender.allow.*:
    description: Overrides all blocked commands, allowing the player to run them.
    default: op

  commanddefender.deny.*:
    description: Overrides all allowed commands, denying the player from running them.
    default: false

  commanddefender.command.*:
    description: Access to all CommandDefender subcommands.
    default: op
    children:
      commanddefender.command: true
      commanddefender.command.reload: true
      commanddefender.command.backup: true
      commanddefender.command.info: true

  commanddefender.command:
    description: Access to the base command, /commanddefender.
    default: true

  commanddefender.command.reload:
    description: Reload the plugin's configuration files.
    default: op

  commanddefender.command.backup:
    description: Backup the plugin's configuration files.
    default: op

  commanddefender.command.info:
    description: View info about the plugin.
    default: true

  commanddefender.bypass-colon-blocker:
    description: Allows the user to bypass the 'block-colons' setting.
    default: op