#   ___                                                _ .___          ,__                     _
# .'   \   __.  , _ , _   , _ , _     ___  , __     ___/ /   `    ___  /  `   ___  , __     ___/   ___  .___
# |      .'   \ |' `|' `. |' `|' `.  /   ` |'  `.  /   | |    | .'   ` |__  .'   ` |'  `.  /   | .'   ` /   \
# |      |    | |   |   | |   |   | |    | |    | ,'   | |    | |----' |    |----' |    | ,'   | |----' |   '
# `.__,  `._.' /   '   / /   '   / `.__/| /    | `___,' /---/  `.___, |    `.___, /    | `___,' `.___, /
# Welcome to CommandDefender's settings.yml file - this is the main configuration where you can change a lot
# of settings to make CommandDefender best suit your server's requirements. Please, read the wiki before
# editing this file (linked below). Thank you!
#
# ----------------------------------------------------------------
# Read the Wiki -> https://github.com/lokka30/CommandDefender/wiki
# ----------------------------------------------------------------

# Create a list of allowed/denied commands ordered by priority.
# Please check the Wiki on how to use this if you are not already familiar. The Wiki URL is linked at the top.
priorities:

  # Setting this to 'false' disables CommandDefender from checking the lists below and thus will not block any commands
  # with exception of the 'block-colons' setting below and also the permissions to block commands which can also be
  # toggled below, see 'enable-allow-deny-permissions'.
  enable-command-blocking: true

  1:
    mode: DENY

    list:
      # Bukkit-provided commands that are able to display installed plugins.
      - '/plugins'
      - '/pl'
      - '/version'
      - '/ver'
      - '/icanhasbukkit'
      - '/about'
      - '/?'
      - '/help'

      # Other commands you may want blocked.
      - '/ehelp'

  # Please do edit/remove this list, as it is only provided by CommandDefender as an example for the argument handling system.
  2:
    mode: DENY

    list:
      - '/abc 123'
      - '/def 456 789'
      - '/example1 *'
      - '/example2'

    deny-message:
      - '%prefix% This is an example deny message which overrides the one set in messages.yml specifically for this list.'

  # If a command is not allowed/blocked in the priorities above, should the command be allowed (ALLOW) or denied (DENY)?
  unlisted: ALLOW

# You can toggle whether CommandDefender checks if the user has a 'force-allow' or 'force-deny'
# permission for each command your users run here.
# Note that these permissions allow/deny only function on the command, not the arguments. e.g. you can only allow/deny
# '/island' with these permissions, you can't block individual arguments such as '/island home'. Note that each prioritised
# list can have a bypass permission though.
enable-allow-deny-permissions: true

# Block colons (:) in the first argument of commands? e.g. block /bukkit:plugins
block-colons: true

# Run the update checker on startup?
# Asynchronous (doesn't halt your server startup), will check once, and only send one warning message if an update is found.
check-for-updates: true

# Do not touch this value unless you are fully aware with what you are doing!
file-version: 2