#################################
#           WARNING!            #
#      ADVANCED USERS ONLY      #
#################################
# This file contains settings   #
# which we do not recommend     #
# you change at all. You should #
# only do so if you are very    #
# advanced at using the plugin. #
# The default advanced settings #
# are the recommended ones.     #
#################################

# Configure the update checker here.
update-checker: #TODO

  # Should the update checker run?
  enabled: true

  # When should the update checker run?
  run:

    # Should the update checker run on startup?
    startup: true

    # At what repeating interval should the update
    # checker run? By default, this is daily. Very
    # useful if you don't restart your server often.
    # Set to 0 to disable the automated update checking.
    on-interval: 1440 # 1 day / 24 hours / 1440 minutes

  # Who should be notified if an update is detected?
  notify:

    # If enabled, it will send a message to all online
    # players who have the update check receive permission
    # from CommandDefender.
    online-players-with-permission: true

    # If enabled, it will send a message to console.
    console: true

# Should server operators bypass all CommandDefender
# processing entirely?
operator-status-bypasses-processing: true

# When specifying commands in the command set lists,
# should they be configured with a starting slash? Example:
# If below is `true`, then `/plugins` will be configured as `/plugins`.
# If below is `false`, then `/plugins` will be configured as `plugins`.
commands-configured-with-starting-slash: true #TODO REMOVE

# All of CommandDefender's event listeners can be configured here.
listeners:

  # This listener intercepts when players are being suggested any
  # tab completions as they type commands.
  # Runs on: Paper (+forks) servers, 1.7+
  async-tab-complete:

    # Should asynchronous tab completion be intercepted by CommandDefender?
    enabled: true

    # Ignore synchronous AsyncTabCompleteEvent calls?
    ignore-sync: true

  # This listener intercepts when players run commands, before they are
  # executed.
  # Runs on: Bukkit (+forks) servers, 1.7+
  player-command-preprocess:

    # If you don't understand the effects of this setting, don't touch it.
    #
    # Should command execution be intercepted by CommandDefender?
    enabled: true

  # This listener intercepts when the server wants to send a player a list
  # of commands that they can run. When permissions are done properly,
  # players won't see commands they're not meant to. Sometimes plugins
  # are poorly programmed which can rule that out. Regardless, CommandDefender
  # allows you to filter all of it. :)
  # Runs on: Bukkit (+forks) servers, 1.13+
  player-command-send:

    # If you don't understand the effects of this setting, don't touch it.
    #
    # Should command suggestions be intercepted by CommandDefender?
    enabled: true

  # This listener intercepts when players are being suggested any
  # tab completions as they type commands.
  # Runs on: Bukkit (+forks) servers, 1.7+
  tab-complete:

    # If you don't understand the effects of this setting, don't touch it.
    #
    # Should synchronous tab completion be intercepted by CommandDefender?
    # Disabling this can yield performance benefits, especially at higher
    # player traffic. Although, disabling this will also prevent the plugin
    # from filtering any synchronous tab completions.
    #
    # If you have no plugins installed which utilize synchronous tab
    # completion, then it would be only beneficial to disable this.
    #
    # Note: CommandDefender will process both async & sync tab completion
    # events, if both are enabled respectively. This is for compatibility
    # purposes.
    enabled: true

    # Ignore asynchronous AsyncTabCompleteEvent calls?
    # (Only affects Paper servers)
    ignore-async: true

# Debug categories to spy on
debug: []

# *** Do NOT modify this section! ***
# Extra data of this file
# for compat, migration, etc.
# *** Do NOT modify this section! ***
file-metadata:
  version: 1